# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smsglobal}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Cooper"]
  s.date = %q{2010-09-19}
  s.description = %q{Ruby gem to send and receive SMS messages via SMSGlobal.}
  s.email = %q{alex@kuperov.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = `git ls-files`.split("\n")
  s.homepage = %q{http://github.com/kuperov/smsglobal}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby interface for SMSGlobal}
  s.test_files = [
    "spec/smsglobal_spec.rb",
    "spec/spec_helper.rb"
  ]

  s.add_development_dependency("rspec", ">= 3.0.0")
  s.add_development_dependency("webmock")
end


